HW 07 Done
Daniil-K/otus-homeworks pull request #6
Opened 2024-02-02 12:04 UTC by Daniil-K

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-02 17:49 UTC, dshemin requested changes

2024-02-02 17:49 UTC, dshemin commented on hw07_file_copying/copy.go
> +	sourceFile, err := os.Open(fromPath)
Важно:

Нет проверки что fromPath и toPath указывают на один и тот же файл. Сразу подскажу: сравнение строк - не верный подход.

2024-02-02 17:49 UTC, dshemin commented on hw07_file_copying/copy.go
> +func Copy(fromPath, toPath string, limit, offset int64) error {
Критично:

Не допускается менять сигнатуры. В реальном проекте, сигнатура метода уже может быть согласована и Ваши коллеги уже пишут код ожидая что она будет работать как было обговорено. Особенно это критично когда меняют местами два соседних аргумента одного типа.

2024-02-02 17:49 UTC, dshemin commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Важно:

У нас может быть нет прав на обращение к фалу или проблема с диском, желательно всё же увидит оригинальную ошибку.

2024-02-02 17:49 UTC, dshemin commented on hw07_file_copying/copy.go
> +		_, err = sourceFile.Seek(offset, 0)
Важно:

Используйте константы https://pkg.go.dev/io#pkg-constants

2024-02-02 17:49 UTC, dshemin commented on hw07_file_copying/copy_test.go
> +		if string(testBytes) != string(targetBytes) {
Важно:

require.Equal()

2024-02-02 17:49 UTC, dshemin commented on hw07_file_copying/copy_test.go
> +	t.Run("limit 10 offset 0", func(t *testing.T) {
Важно:

Лучше использовать табличные тесты тут.

2024-02-02 18:36 UTC, Daniil-K commented on hw07_file_copying/copy.go
> +func Copy(fromPath, toPath string, limit, offset int64) error {
Сигнатура метода не менялась, случайно заменил nil на error, исправил

<img width="514" alt="image" src="https://github.com/Daniil-K/otus-homeworks/assets/38119946/c009d4a4-0698-4bd3-90f1-df2bb021076c">

2024-02-03 05:26 UTC, dshemin requested changes

2024-02-03 05:26 UTC, dshemin commented on hw07_file_copying/copy.go
> +func Copy(fromPath, toPath string, limit, offset int64) error {
Поменяли местами  offset и limit, внимательно посмотрите на сигнатуру которая была и которая у Вас.

2024-02-03 05:31 UTC, dshemin requested changes

2024-02-03 05:31 UTC, dshemin commented on hw07_file_copying/copy.go
> +		_, err = sourceFile.Seek(offset, indexStartOfFile)
Критично:

Вам надо было использовать io.SeekStart. Константы уже есть я в комментарии дал на них ссылку https://pkg.go.dev/io#pkg-constants

2024-02-03 08:01 UTC, Daniil-K commented on hw07_file_copying/copy.go
> +		_, err = sourceFile.Seek(offset, indexStartOfFile)
Проблема решил

2024-02-05 16:38 UTC, dshemin approved these changes

2024-02-05 16:55 UTC, merged