HW 08 Done
Daniil-K/otus-homeworks pull request #8
Opened 2024-02-24 16:18 UTC by Daniil-K

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-28 01:07 UTC, dshemin requested changes

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +	valueBytes, err := os.ReadFile(file)
Важно:

Вычитываем весь файл в память, чтобы забрать только первую строку. Не самое оптимальное решение.

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +		return &EnvValue{"", true}, nil
Важно:

Не используйте сокращённую форму инициализации структур.

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/env_reader_test.go
> +	require.Nil(t, err)
Важно:

Для ошибок лучше использовать require.NoError.

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/env_reader_test.go
> +	testdata := make(Environment)
Важно:

Можно убрать make и просто сразу создать структуру с данными
```
testdata= Environemnt {
    "BAR": EnvValue{"bar", false},
    // ...
}
```

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/env_reader_test.go
> +	tmp, err := os.MkdirTemp("", "temp")
Важно:

Лучше использовать https://pkg.go.dev/testing@go1.19.13#T.TempDir

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	if len(cmd) == 0 {
Важно:

Данную проверку лучше сделать до того, как мы будем оперировать переменными окружения.

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +	command.Stdout = os.Stdout
Критично:

Не перенаправлени stdin.

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		_ = os.Unsetenv(key)
Критично:

Тут мы манипулируем переменными окружения текущего процесса, а надо менять для того, который пораждаем.

2024-02-28 01:07 UTC, dshemin commented on hw08_envdir_tool/executor_test.go
> +	if err != nil {
Важно:

Используйте require.NoError

2024-02-28 15:00 UTC, Daniil-K commented on hw08_envdir_tool/executor.go
> +		_ = os.Unsetenv(key)
Не совсем понял как это исправить, подскажите, пожалуйста

2024-02-29 04:43 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		_ = os.Unsetenv(key)
Вот есть релевантный пример: https://pkg.go.dev/os/exec#example-Command-Environment

2024-02-29 04:45 UTC, dshemin requested changes

2024-02-29 04:45 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +	valueBytes, err := os.ReadFile(file)
Обратите внимание на данный комментарий.

2024-03-10 17:52 UTC, dshemin approved these changes

2024-03-10 17:52 UTC, dshemin commented on hw08_envdir_tool/env_reader.go
> +	}
Важно:

Нет обработки ошибки сканирования.

2024-03-10 17:52 UTC, dshemin commented on hw08_envdir_tool/executor.go
> +		if errors.As(err, &e) {
Важно:

1. Зачем нам тут проверка на exec.Error?
2. зачем нам вообще проверка на конкретный тип ошибки в котором нет статус кода? Что если поведение поменяется и Run начнёт возвращать не только два типа ошибок, которые Вы проверяете?

Просто проверьте все нужные типы, а на все остальные возвращайте 127

2024-03-17 14:51 UTC, merged